FROM ekhurtado/smia:latest-alpine-base

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY smia_ism /smia_ism

WORKDIR /smia_ism

CMD ["python3", "-u", "smia_ism_starter.py"]
#CMD [ "tail", "-f", "/dev/null"]