
services:

  # ----------------------------------------
  # AAS Infrastructure services (from BaSyx)
  # ----------------------------------------
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name: aas-env
    environment:
      - SERVER_PORT=8081
    volumes:
      - ./aas:/application/aas
      - ./basyx/aas-env.properties:/application/application.properties
    ports:
      - '8081:8081'
    restart: always
    depends_on:
      aas-registry:
        condition: service_healthy
      sm-registry:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - smia-cedri-net

  aas-registry:
    image: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: aas-registry
    ports:
      - '8082:8080'
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./basyx/aas-registry.yml:/workspace/config/application.yml
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - smia-cedri-net

  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: sm-registry
    ports:
      - '8083:8080'
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./basyx/sm-registry.yml:/workspace/config/application.yml
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - smia-cedri-net

  mongo:
    image: mongo:5.0.10
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    restart: always
    healthcheck:
      test: mongo
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smia-cedri-net

  aas-web-ui:
    image: eclipsebasyx/aas-gui:SNAPSHOT
    container_name: aas-ui
    ports:
      - '3000:3000'
    environment:
      AAS_REGISTRY_PATH: http://localhost:8082/shell-descriptors
      SUBMODEL_REGISTRY_PATH: http://localhost:8083/submodel-descriptors
      AAS_REPO_PATH: http://localhost:8081/shells
      SUBMODEL_REPO_PATH: http://localhost:8081/submodels
      CD_REPO_PATH: http://localhost:8081/concept-descriptions
      AAS_DISCOVERY_PATH: http://localhost:8084/lookup/shells
      PRIMARY_COLOR: '#347EE1'
      LOGO_PATH: SMIA_logo.ico
    restart: always
    depends_on:
      aas-env:
        condition: service_healthy
    volumes:
      - ./logo:/usr/src/app/dist/Logo
    networks:
      - smia-cedri-net



  # ----------------------------
  # SMIA Infrastructure services
  # ----------------------------
  xmpp-server:
    image: ghcr.io/processone/ejabberd
    container_name: ejabberd
    environment:
      - ERLANG_NODE_ARG=admin@ejabberd
      - ERLANG_COOKIE=dummycookie123
      - CTL_ON_CREATE=! register admin localhost asd
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
    volumes:
      - ./xmpp_server/ejabberd.yml:/opt/ejabberd/conf/ejabberd.yml
    healthcheck:
      test: netstat -nl | grep -q 5222
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - smia-cedri-net

  smia-kb:
    image: ekhurtado/smia-tools:latest-smia-kb
    container_name: smia-kb
    ports:
      - '8090:8080'
    environment:
      - AAS_ENV_IP=http://aas-env:8081
      #- SELF_EXTRACT_CSS=yes
    depends_on:   # It does not depend on the AAS environment, but is added to correctly obtain all the data during the start-up
      aas-env:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://smia-kb:8080/api/v3/ui/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - smia-cedri-net

  smia-ism:
    image: ekhurtado/smia-tools:latest-smia-ism
    container_name: smia-ism
    environment:
      - AAS_MODEL_NAME=SMIA_InfrastructureServicesManager.aasx
      - AGENT_ID=smia-ism@ejabberd
      - AGENT_PSSWD=gciscedri1234
      - SMIA_KB_IP=http://smia-kb:8080
    depends_on:
      xmpp-server:
        condition: service_healthy
      smia-kb:
        condition: service_healthy
    healthcheck:
      test: exit 0
      start_period: 15s
    volumes:
      - ./aas:/smia_archive/config/aas
    networks:
      - smia-cedri-net



  # -----------------------------
  # CeDRI Infrastructure services
  # -----------------------------
  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - 1880:1880
    volumes:
      - ./nodered:/data
    networks:
      - smia-cedri-net

networks:
  smia-cedri-net:
    name: smia_cedri_use_case_net
