#version: "2"

services:

  smia-ism:
    image: ekhurtado/smia-tools:latest-smia-ism
    container_name: smia-ism
    environment:
      - AAS_MODEL_NAME=SMIA_InfrastructureServicesManager.aasx
      - AGENT_ID=smia-ism@ejabberd
      - AGENT_PSSWD=gcis1234
    depends_on:
      xmpp-server:
        condition: service_healthy
    volumes:
      - ./aas:/smia_archive/config/aas

  xmpp-server:
    image: ghcr.io/processone/ejabberd
    container_name: ejabberd
    environment:
      - ERLANG_NODE_ARG=admin@ejabberd
      - ERLANG_COOKIE=dummycookie123
      - CTL_ON_CREATE=! register admin localhost asd
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
    volumes:
      - ./xmpp_server/ejabberd.yml:/opt/ejabberd/conf/ejabberd.yml
    healthcheck:
      test: netstat -nl | grep -q 5222
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10




