from smia import GeneralUtils
from smia.utilities.fipa_acl_info import FIPAACLInfo, ACLSMIAOntologyInfo


class SMIAACLMessageInfo:
    """
    This class contains the information related to FIPA-ACL messages.
    """

    # Individual templates
    SMIA_ACL_INFRASTRUCTURE_REQUEST_TEMPLATE = GeneralUtils.create_acl_template(
        FIPAACLInfo.FIPA_ACL_PERFORMATIVE_REQUEST, ACLSMIAOntologyInfo.ACL_ONTOLOGY_AAS_INFRASTRUCTURE_SERVICE)
    SMIA_ACL_INFRASTRUCTURE_QUERY_REF_TEMPLATE = GeneralUtils.create_acl_template(
        FIPAACLInfo.FIPA_ACL_PERFORMATIVE_QUERY_REF, ACLSMIAOntologyInfo.ACL_ONTOLOGY_AAS_INFRASTRUCTURE_SERVICE)
    SMIA_ACL_INFRASTRUCTURE_QUERY_IF_TEMPLATE = GeneralUtils.create_acl_template(
        FIPAACLInfo.FIPA_ACL_PERFORMATIVE_QUERY_IF, ACLSMIAOntologyInfo.ACL_ONTOLOGY_AAS_INFRASTRUCTURE_SERVICE)

    # Complex templates
    SMIA_ISM_ACL_INFRASTRUCTURE_SERVICE_TEMPLATE = (
        SMIA_ACL_INFRASTRUCTURE_REQUEST_TEMPLATE | SMIA_ACL_INFRASTRUCTURE_QUERY_REF_TEMPLATE |
        SMIA_ACL_INFRASTRUCTURE_QUERY_IF_TEMPLATE
    )