# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.datatypes import ReferenceIRI  # noqa: F401,E501
from swagger_server.models.skill_parameter import SkillParameter  # noqa: F401,E501
from swagger_server import util


class Skill(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, iri: ReferenceIRI=None, name: str=None, accessible_through: List[ReferenceIRI]=None, has_parameter: List[SkillParameter]=None):  # noqa: E501
        """Skill - a model defined in Swagger

        :param iri: The iri of this Skill.  # noqa: E501
        :type iri: ReferenceIRI
        :param name: The name of this Skill.  # noqa: E501
        :type name: str
        :param accessible_through: The accessible_through of this Skill.  # noqa: E501
        :type accessible_through: List[ReferenceIRI]
        :param has_parameter: The has_parameter of this Skill.  # noqa: E501
        :type has_parameter: List[SkillParameter]
        """
        self.swagger_types = {
            'iri': ReferenceIRI,
            'name': str,
            'accessible_through': List[ReferenceIRI],
            'has_parameter': List[SkillParameter]
        }

        self.attribute_map = {
            'iri': 'iri',
            'name': 'name',
            'accessible_through': 'accessibleThrough',
            'has_parameter': 'hasParameter'
        }
        self._iri = iri
        self._name = name
        self._accessible_through = accessible_through
        self._has_parameter = has_parameter

    @classmethod
    def from_dict(cls, dikt) -> 'Skill':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Skill of this Skill.  # noqa: E501
        :rtype: Skill
        """
        return util.deserialize_model(dikt, cls)

    @property
    def iri(self) -> ReferenceIRI:
        """Gets the iri of this Skill.


        :return: The iri of this Skill.
        :rtype: ReferenceIRI
        """
        return self._iri

    @iri.setter
    def iri(self, iri: ReferenceIRI):
        """Sets the iri of this Skill.


        :param iri: The iri of this Skill.
        :type iri: ReferenceIRI
        """
        if iri is None:
            raise ValueError("Invalid value for `iri`, must not be `None`")  # noqa: E501

        self._iri = iri

    @property
    def name(self) -> str:
        """Gets the name of this Skill.


        :return: The name of this Skill.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Skill.


        :param name: The name of this Skill.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def accessible_through(self) -> List[ReferenceIRI]:
        """Gets the accessible_through of this Skill.

        Through which skill interfaces is the capability accessible.  # noqa: E501

        :return: The accessible_through of this Skill.
        :rtype: List[ReferenceIRI]
        """
        return self._accessible_through

    @accessible_through.setter
    def accessible_through(self, accessible_through: List[ReferenceIRI]):
        """Sets the accessible_through of this Skill.

        Through which skill interfaces is the capability accessible.  # noqa: E501

        :param accessible_through: The accessible_through of this Skill.
        :type accessible_through: List[ReferenceIRI]
        """

        self._accessible_through = accessible_through

    @property
    def has_parameter(self) -> List[SkillParameter]:
        """Gets the has_parameter of this Skill.

        The associated skill parameters.  # noqa: E501

        :return: The has_parameter of this Skill.
        :rtype: List[SkillParameter]
        """
        return self._has_parameter

    @has_parameter.setter
    def has_parameter(self, has_parameter: List[SkillParameter]):
        """Sets the has_parameter of this Skill.

        The associated skill parameters.  # noqa: E501

        :param has_parameter: The has_parameter of this Skill.
        :type has_parameter: List[SkillParameter]
        """

        self._has_parameter = has_parameter
